---
- name: create install directory
  file: path={{ install_dir }} state=directory
- name: unarchive binary to install directory
  unarchive: src={{ binary_src_dir }}/{{ binary_name }} dest={{ install_dir }}
- name: setup env var >>> GOROOT
  shell: "sed -i '/GOROOT/d' /etc/bashrc && sed -i '$a export GOROOT={{install_dir}}/{{app_name}}' /etc/bashrc"
- name: setup env var >>> PATH
  shell: "sed -i '$a export PATH=$PATH:$GOROOT/bin' /etc/bashrc && source /etc/bashrc"

